# Optional Backend for AI Forensics Tool
import os
import io
import datetime
from flask import Flask, request, jsonify, send_file
from fpdf import FPDF
from PIL import Image, ImageChops, ImageEnhance
import numpy as np

app = Flask(__name__, static_url_path='', static_folder='.')

# Configuration
UPLOAD_FOLDER = './uploads'
MAX_CONTENT_LENGTH = 16 * 1024 * 1024 # 16MB
os.makedirs(UPLOAD_FOLDER, exist_ok=True)

@app.route('/')
def root():
    return app.send_static_file('index.html')

@app.route('/analyze')
def tool():
    return app.send_static_file('analyze.html')

def perform_ela(image_path, quality=90):
    """
    Generates an Error Level Analysis (ELA) image.
    """
    original = Image.open(image_path).convert('RGB')
    
    # Save as temporary JPG with known quality
    temp_path = image_path + '.ela.tmp.jpg'
    original.save(temp_path, 'JPEG', quality=quality)
    
    # Open temp and compare
    resaved = Image.open(temp_path)
    ela_image = ImageChops.difference(original, resaved)
    
    # Scale to make it visible
    extrema = ela_image.getextrema()
    max_diff = max([ex[1] for ex in extrema])
    if max_diff == 0:
        max_diff = 1
    scale = 255.0 / max_diff
    
    ela_image = ImageEnhance.Brightness(ela_image).enhance(scale)
    
    # Cleanup
    try:
        os.remove(temp_path)
    except:
        pass
        
    return ela_image

@app.route('/api/analyze', methods=['POST'])
def analyze_image():
    """
    Server-side analysis endpoint.
    Reference 2: Server-Side Metadata & ELA
    """
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400
        
    file = request.files['file']
    if file.filename == '':
        return jsonify({"error": "No selected file"}), 400

    try:
        # Save temp file
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        filename = f"{timestamp}_{file.filename}"
        filepath = os.path.join(UPLOAD_FOLDER, filename)
        file.save(filepath)

        # Basic Info
        img = Image.open(filepath)
        width, height = img.size
        format = img.format
        
        # ELA Analysis (Mock result relative variance)
        ela_img = perform_ela(filepath)
        ela_np = np.array(ela_img)
        ela_variance = float(np.var(ela_np))

        return jsonify({
            "status": "success",
            "server_analysis": {
                "format": format,
                "dimensions": [width, height],
                "ela_variance": round(ela_variance, 2),
                "message": "Server-side analysis complete."
            }
        })
    except Exception as e:
        return jsonify({"error": str(e)}), 500

@app.route('/api/report', methods=['POST'])
def generate_report():
    """
    Generates a PDF report.
    Reference 1: PDF Report Generation
    Expected POST data: multipart/form-data with 'file' and 'data' (JSON string)
    """
    if 'file' not in request.files:
        return jsonify({"error": "No file part"}), 400

    file = request.files['file']
    confidence = request.form.get('confidence', 'N/A')
    verdict = request.form.get('verdict', 'Unknown')
    
    try:
        # Save temp file for report
        timestamp = datetime.datetime.now().strftime("%Y%m%d%H%M%S")
        filename = f"report_{timestamp}_{file.filename}"
        filepath = os.path.join(UPLOAD_FOLDER, filename)
        file.save(filepath)
        
        # Create PDF
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font('Helvetica', 'B', 20)
        pdf.cell(0, 10, 'AI Image Forensics Report', new_x="LMARGIN", new_y="NEXT", align='C')
        pdf.ln(10)
        
        # Image
        pdf.set_font('Helvetica', '', 12)
        pdf.cell(0, 10, f'File: {file.filename}', new_x="LMARGIN", new_y="NEXT")
        pdf.cell(0, 10, f'Date: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', new_x="LMARGIN", new_y="NEXT")
        pdf.ln(5)
        
        # Insert Image (scaled)
        pdf.image(filepath, w=100, x=55) # Centered-ish
        pdf.ln(10)

        # Results
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(0, 10, 'Analysis Results', new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font('Helvetica', '', 12)
        pdf.cell(0, 10, f'Integrity Score: {confidence}', new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(220, 50, 50) if 'Likely AI' in verdict else pdf.set_text_color(50, 150, 50)
        pdf.cell(0, 10, f'Verdict: {verdict}', new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(0, 0, 0)
        
        # Footer
        pdf.set_y(-30)
        pdf.set_font('Helvetica', 'I', 8)
        pdf.cell(0, 10, 'Generated by AI Forensics Tool - naveencyber.gt.tc', align='C')

        # Output
        pdf_out = pdf.output()
        binary_pdf = io.BytesIO(pdf_out)
        
        return send_file(
            binary_pdf,
            as_attachment=True,
            download_name=f"Forensics_Report_{timestamp}.pdf",
            mimetype='application/pdf'
        )

    except Exception as e:
        return jsonify({"error": str(e)}), 500

if __name__ == '__main__':
    app.run(debug=True, port=5000)
